#ident "%W% %E% %Q%"
###########################################################################
# Sample makefile for sub-makes in one directory
###########################################################################
SRCROOT=	../..
RULESDIR=	RULES
include		$(SRCROOT)/$(RULESDIR)/rules.top
###########################################################################

MK_FILES=	dump.mk isodump.mk isoinfo.mk isovfy.mk
#XMK_FILE=	Makefile.man

###########################################################################
include		$(SRCROOT)/$(RULESDIR)/rules.mks
###########################################################################
